version: '2'
services:
  openvpn:
    container_name: openvpn_container
    image: kylemanna/openvpn
    volumes:
      - ./openvpn_data/conf:/etc/openvpn
    ports:
      - "1194:1194/udp"
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
