version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn_container
    ports:
     - "1194:1194/udp"
    restart: unless-stopped
    volumes:
     - $PWD/openvpn_data/conf:/etc/openvpn
