version: '3'
services:
  zabbix_db:
    container_name: zabbix_db_container
    image: mysql:5.7
    volumes:
      - "./zabbix_db_data/data:/var/lib/mysql"
      - "./zabbix_db_data/conf/create.sql:/docker-entrypoint-initdb.d/zabbix.sql"
    ports:
      - 3306:3306
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: zabbix_user
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_DATABASE: zabbix_db
    networks:
      - zabbix_net

  zabbix_web:
    container_name: zabbix_web_container
    image: zabbix
    build: .
    volumes:
      - ./zabbix_web_data:/usr/share/zabbix
    ports:
      - 80:80
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
    depends_on:
      - zabbix_db
    restart: unless-stopped
    networks:
      - zabbix_net

networks:
  zabbix_net:
