[package]
name = "crates-base64"
version = "0.1.0"
authors = ["Camilo Pifano Herrera <camilopifano@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
