version: "3.7"
services:
  samba:
    image: dperson/samba
    restart: unless-stopped
    command: '-u "pi;password" -s "DATOS;/DATOS;yes;no"'
    stdin_open: true
    tty: true
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${DATOS}:/DATOS

  plex:
    image: jaymoulin/plex:1.30.1.6562
    expose:
      - 32400
      - 33400
    ports:
     - 32400:32400
     - 33400:33400
    volumes:
      - ${DATOS}/plexserver/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${DATOS}/media:/media
      - ${DATOS}/plexserver/tmp:/tmp
    restart: unless-stopped
    network_mode: "host"