version: '3'

services:
  mysql:
    container_name: mysql_container
    image: mysql:5.7
    volumes:
       - $PWD/mysql_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: wp_database
       MYSQL_USER: wp_db_user
       MYSQL_PASSWORD: wp_db_password
    ports:
      - "3306:3306"
    networks:
      - wp_net

  wordpress:
    container_name: wordpress_container
    volumes:
      - $PWD/wordpress_data:/var/www/html
    depends_on:
      - mysql
    image: wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wp_database
      WORDPRESS_DB_USER: wp_db_user
      WORDPRESS_DB_PASSWORD: wp_db_password
    networks:
      - wp_net
      
networks:
  wp_net:
