version: '3'

services:
  wordpress_db:
    container_name: wordpress_db_container
    image: mysql:5.7
    volumes:
      - ./wordpress_db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wp_db_user
      MYSQL_PASSWORD: wp_db_password
    restart: unless-stopped
    networks:
      - wordpress_net

  wordpress_web:
    container_name: wordpress_web_container
    image: wordpress
    volumes:
      - ./wordpress_web_data:/var/www/html
    ports:
      - 80:80
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_NAME: wp_database
      WORDPRESS_DB_USER: wp_db_user
      WORDPRESS_DB_PASSWORD: wp_db_password
    depends_on:
      - wordpress_db
    restart: unless-stopped
    networks:
      - wordpress_net

networks:
  wordpress_net:
