version: '3'
services:
  nextcloud_db:
    container_name: nextcloud_db_container
    image: mariadb
    volumes:
      - ./nextcloud_db_data:/mnt/mariadb-data
    ports:
      - 3307:3307
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: nextcloud_db_user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: nextcloud
      TRANSACTION_ISOLATION: READ-COMMITTED
    restart: unless-stopped
    networks:
      - nextcloud_network

  nextcloud_web:
    container_name: nextcloud_web_container
    image: nextcloud_db
    volumes:
      - ./nextcloud_web_data/nextcloud:/var/www/html
      - ./nextcloud_web_data/app/data:/mnt/nextcloud-data
      - ./nextcloud_web_data/app/config:/mnt/nextcloud-config
      - ./nextcloud_web_data/app/apps:/var/www/html/apps
      - ./nextcloud_web_data/app/custom_apps:/var/www/html/custom_apps
      - ./nextcloud_web_data/app/themes:/var/www/html/themes
    ports:
      - 80:80
      - 8080:8080
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      MYSQL_HOST: nextcloud_db
    depends_on:
      - nextcloud_db
    restart: unless-stopped
    networks:
      - nextcloud_network

networks:
  nextcloud_network:
