version: '3.7'
services:
  portainer:
    container_name: portainer_container
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    ports:
      - 8000:8000
      - 9000:9000
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
    restart: unless-stopped
