version: '3'
services:
  gitea_db:
    container_name: gitea_db_container
    image: mysql:5.7
    volumes:
       - ./gitea_db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gitea_database
      MYSQL_USER: gitea_db_user
      MYSQL_PASSWORD: gitea_db_password
    restart: unless-stopped
    networks:
      - gitea_net

  gitea_web:
    container_name: gitea_web_container
    image: gitea/gitea:1.12.4
    hostname: 'gitea.selfmanaged.com'
    volumes:
      - ./gitea_web_data:/data
    ports:
      - 8080:3000
      - 8443:443
      - 822:22
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
    depends_on:
      - gitea_db
    restart: unless-stopped
    networks:
      - gitea_net

networks:
  gitea_net:
