version: '3'
services:
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    volumes:
      - ./mongodb_data:/data/db
      - ./mongodb_config:/data/configdb
    ports:
      - 27017:27017
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
    restart: unless-stopped
