version: '3'
services:
  netdata:
    container_name: netdata_container
    image: netdata/netdata
    hostname: netdata.selfmanaged.com
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 19999:19999
    enviroment:
      TZ: 'America/Argentina/Buenos_Aires'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
