version: '3'

services:
  prestashop_db:
    container_name: prestashop_db_container
    image: mysql:5.7
    volumes:
      - ./prestashop_db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: prestashop_database
      MYSQL_USER: prestashop_user
      MYSQL_PASSWORD: prestashop_pass
    restart: unless-stopped
    networks:
      - prestashop_net

  prestashop_web:
    container_name: prestashop_web_container
    image: prestashop/prestashop
    volumes:
      - ./prestashop_web_data:/var/www/html
    ports:
      - 80:80
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      DB_SERVER: prestashop_db
      DB_USER: prestashop_user
      DB_PASSWD: prestashop_pass
      DB_NAME: prestashop_database
    depends_on:
      - prestashop_db
    restart: unless-stopped
    networks:
      - prestashop_net

networks:
  prestashop_net:
