version: '3'
services:
  mysql:
    container_name: mysql_container
    image: mysql:5.7
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    enviroment:
      TZ: 'America/Argentina/Buenos_Aires'
      MYSQL_ROOT_PASSWORD: my_password
    restart: unless-stopped
